[package]
name = "ailang_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ailang_core = { path = "../ailang_core", default-features = false }

[features]
default = []
gpu-wgpu = ["ailang_core/gpu-wgpu"]